name: mcc
version: 0.1.0.0
github: jmorag/mcc
synopsis: A microc compiler in Haskell
author: "Joseph Morag"
license-file: LICENSE
category: Compilers/Interpreters
ghc-options: -Wall 
             -fno-warn-name-shadowing 
             -Wcompat
             -Wincomplete-uni-patterns
extra-source-files: README.md

dependencies:
    - base >= 4.7 && < 5
    - happy
    - alex
    - mtl >= 2.2 && <= 3
    - containers
    - text
    - string-conversions
    - directory
    - process
    - unix
    - filepath
    - bytestring
    - prettyprinter
    - pretty-simple
    - llvm-hs-pure
    - llvm-hs-pretty

default-extensions: OverloadedStrings, LambdaCase

build-tools: alex, happy

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies: 
      - optparse-applicative
      - mcc

tests:
  testall:
    main: Testall.hs
    source-dirs: tests
    dependencies:
        - tasty
        - tasty-golden
        - mcc
