resolver: lts-13.14

packages:
- '.'

extra-deps:
# until they merge bugfix into hackage we need to use the version on github
# - llvm-hs-pure-7.0.0
- github: llvm-hs/llvm-hs
  commit: 1b6bf6f3a731c924f3538ed8f3faebaf06ff152d
  subdirs:
    - llvm-hs-pure
- llvm-hs-pretty-0.6.1.0

nix:
    enable: true
    packages: [llvm_6, clang_6]
